language: java
script:
  - ant compile
  - ant test
  - ant make
  - sudo apt-get install sshpass
  - sshpass -p "palipoor976@gmail.com" scp -o StrictHostKeyChecking=no build/jar/HOOOOO.jar 94105611@198.144.184.34:/home/94105611/HOOOOO.jar
  - sshpass -p "palipoor976@gmail.com" ssh 94105611@198.144.184.34 pkill java
  - sshpass -p "palipoor976@gmail.com" ssh 94105611@198.144.184.34 "nohup java -jar /home/94105611/HOOOOO.jar &"